name: PersonalDragon
version: 1.1.0
main: com.tuservidor.personaldragon.PersonalDragonPlugin
api-version: "1.21"

commands:
  pdragon:
    description: Dragón personalizable montable (no-vanilla)
    usage: /pdragon

permissions:
  personaldragon.use:
    default: true
